//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatTest.Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public int StoryID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public System.DateTime PostedOn { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
